#!/usr/bin/env bash

# wget "https://raw.githubusercontent.com/TiagoDGomes/server-manager/main/run" -q -O - | bash -

echo "- Cleaning..."
rm -rf /tmp/server-manager-main/
echo "- Check unzip..."
apt-get install -y unzip > /dev/null
echo "- Download..."
wget -q "https://github.com/TiagoDGomes/server-manager/archive/refs/heads/main.zip" -O /tmp/sm.zip 
echo "- Extracting..."
unzip -q /tmp/sm.zip -d /tmp/
echo "- Set attributes..."
chmod -R +x /tmp/server-manager-main/
cd /tmp/server-manager-main/
/bin/bash /tmp/server-manager-main/server-manager