#!/usr/bin/env bash

echo "- Cleaning..."
rm -rf /opt/server-manager-main/
echo "- Check unzip..."
apt-get install -y unzip > /dev/null
echo "- Download..."
wget -q "https://github.com/TiagoDGomes/server-manager/archive/refs/heads/main.zip" -O /tmp/sm.zip 
echo "- Extracting..."
unzip -q /tmp/sm.zip -d /opt/
echo "- Cleaning old version..."
rm -rf /opt/server-manager
echo "- Moving..."
mv /opt/server-manager-main /opt/server-manager
echo "- Set attributes..."
chmod -R +x /opt/server-manager/
echo "- Cleaning installer..."
rm /opt/server-manager/server-manager-installer