#!/usr/bin/env bash


apt-get install -y unzip
wget "https://github.com/TiagoDGomes/server-manager/archive/refs/heads/main.zip" -O /tmp/sm.zip 
unzip /tmp/sm.zip -d /opt/
mv /opt/server-manager-main /opt/server-manager/
chmod -R +x /opt/server-manager/
rm /opt/server-manager/server-manager-installer