#!/usr/bin/env bash

VERSION=2
. lang/default



shw_grey () {
    echo $(tput bold)$(tput setaf 0) $@ $(tput sgr 0)
}

shw_norm () {
    echo $(tput bold)$(tput setaf 9) $@ $(tput sgr 0)
}

shw_info () {
    echo $(tput bold)$(tput setaf 4) $@ $(tput sgr 0)
}

shw_warn () {
    echo $(tput bold)$(tput setaf 2) $@ $(tput sgr 0)
}

shw_err ()  {
    echo $(tput bold)$(tput setaf 1) $@ $(tput sgr 0)
}


backup_file () {
    [ ! -f "$1.sm-backup" ] && cp "$1" "$1.sm-backup"
}

restore_file () {
    [ -f "$1.sm-backup" ] && cp "$1.sm-backup" "$1"
}

subnet () {
    if [ $# -ne 1 ]; then
        echo ""
        return 1
    fi
    [ $1 == 8 ] && echo "255.0.0.0" ; # 0" ; # 16777214
    [ $1 == 9 ] && echo "255.128.0.0" ; # 2 (0)" ; # 8388606
    [ $1 == 10 ] && echo "255.192.0.0" ; # 4 (2)" ; # 4194302
    [ $1 == 11 ] && echo "255.224.0.0" ; # 8 (6)" ; # 2097150
    [ $1 == 12 ] && echo "255.240.0.0" ; # 16 (14)" ; # 1048574
    [ $1 == 13 ] && echo "255.248.0.0" ; # 32 (30)" ; # 524286
    [ $1 == 14 ] && echo "255.252.0.0" ; # 64 (62)" ; # 262142
    [ $1 == 15 ] && echo "255.254.0.0" ; # 128 (126)" ; # 131070
    [ $1 == 16 ] && echo "255.255.0.0" ; # 256 (254)" ; # 65534
    [ $1 == 17 ] && echo "255.255.128.0" ; # 512 (510)" ; # 32766
    [ $1 == 18 ] && echo "255.255.192.0" ; # 1024 (1022)" ; # 16382
    [ $1 == 19 ] && echo "255.255.224.0" ; # 2048 (2046)" ; # 8190
    [ $1 == 20 ] && echo "255.255.240.0" ; # 4096 (4094)" ; # 4094
    [ $1 == 21 ] && echo "255.255.248.0" ; # 8192 (8190)" ; # 2046
    [ $1 == 22 ] && echo "255.255.252.0" ; # 16384 (16382)" ; # 1022
    [ $1 == 23 ] && echo "255.255.254.0" ; # 32768 (32766)" ; # 510
    [ $1 == 24 ] && echo "255.255.255.0" ; # 65536 (65534)" ; # 254
    [ $1 == 25 ] && echo "255.255.255.128" ; # 131072 (131070)" ; # 126
    [ $1 == 26 ] && echo "255.255.255.192" ; # 262144 (262142)" ; # 62
    [ $1 == 27 ] && echo "255.255.255.224" ; # 524288 (524286)" ; # 30
    [ $1 == 28 ] && echo "255.255.255.240" ; # 1048576 (1048574)" ; # 14
    [ $1 == 29 ] && echo "255.255.255.248" ; # 2097152 (2097150)" ; # 6
    [ $1 == 30 ] && echo "255.255.255.252" ; # 4194304 (4194302)" ; # 2   
}

info_net_addr_net(){
    ip=$1; mask=$2
    IFS=. read -r i1 i2 i3 i4 <<< "$ip"
    IFS=. read -r m1 m2 m3 m4 <<< "$mask"
    echo "$((i1 & m1)).$((i2 & m2)).$((i3 & m3)).$((i4 & m4))"
}
info_net_addr_brd(){
    ip=$1; mask=$2
    IFS=. read -r i1 i2 i3 i4 <<< "$ip"
    IFS=. read -r m1 m2 m3 m4 <<< "$mask"
    echo "$((i1 & m1 | 255-m1)).$((i2 & m2 | 255-m2)).$((i3 & m3 | 255-m3)).$((i4 & m4 | 255-m4))"
}

info_net_addr_first_ip(){
    ip=$1; mask=$2
    IFS=. read -r i1 i2 i3 i4 <<< "$ip"
    IFS=. read -r m1 m2 m3 m4 <<< "$mask"
    echo "$((i1 & m1)).$((i2 & m2)).$((i3 & m3)).$(((i4 & m4)+1))"
}

info_net_addr_last_ip(){
    ip=$1; mask=$2
    IFS=. read -r i1 i2 i3 i4 <<< "$ip"
    IFS=. read -r m1 m2 m3 m4 <<< "$mask"
    echo "$((i1 & m1 | 255-m1)).$((i2 & m2 | 255-m2)).$((i3 & m3 | 255-m3)).$(((i4 & m4 | 255-m4)-1))"
}

# info_net_addr_net 10.10.128.2 $(subnet 19)
# info_net_addr_brd 10.10.128.2 $(subnet 19)
# info_net_addr_first_ip 10.10.128.2 $(subnet 19)
# info_net_addr_last_ip 10.10.128.2 $(subnet 19)


inputbox(){
    whiptail --title "$1" \
                --inputbox "\n$2\n\n" $4 $5 "$6" \
                --backtitle "$3" 3>&1 1>&2 2>&3
}

_inputmenu_choice=()
inputmenu_show(){
    whiptail --title "$1" \
                --menu "\n$2\n\n" $4 $5 $6 "${_inputmenu_choice[@]}" \
                --backtitle "$3" 3>&1 1>&2 2>&3
    _inputmenu_choice=()
}
inputmenu_add(){
    _inputmenu_choice+=("$1")
    _inputmenu_choice+=("$2")
}

