#!/usr/bin/env bash

VERSION=2
. lang/default



shw_grey () {
    echo $(tput bold)$(tput setaf 0) $@ $(tput sgr 0)
}

shw_norm () {
    echo $(tput bold)$(tput setaf 9) $@ $(tput sgr 0)
}

shw_info () {
    echo $(tput bold)$(tput setaf 4) $@ $(tput sgr 0)
}

shw_warn () {
    echo $(tput bold)$(tput setaf 2) $@ $(tput sgr 0)
}
shw_err ()  {
    echo $(tput bold)$(tput setaf 1) $@ $(tput sgr 0)
}


backup_file () {
    [ ! -f "$1.sm-backup" ] && cp "$1" "$1.sm-backup"
}

restore_file () {
    [ -f "$1.sm-backup" ] && cp "$1.sm-backup" "$1"
}