#!/usr/bin/env bash

. lang/default

IPV4_ADDRESS_TEST_GATEWAY="8.8.8.8"
IPV6_ADDRESS_TEST_GATEWAY="2001:4860:4860::8888"

interface_choice=()
INTERFACES=$(ip link | grep "UP" | grep "BROADCAST" |  cut -d ":" -f2)
for n in $INTERFACES; do
   mac=$(cat /sys/class/net/$n/address)
   device_name=""
   if [ -f "/sys/class/net/$n/device/uevent" ]; then
      slot_name=$(cat /sys/class/net/$n/device/uevent | grep "PCI_SLOT_NAME" | cut -d "=" -f 2)
      device_name=$(lspci -s "$slot_name" | cut -d ":" -f 3)
      device_name=`echo $device_name | sed 's/ *$//g'`  
   fi
   interface_choice+=("$n")
   interface_choice+=("[$mac] $device_name")
done
INTERFACE=$(whiptail --backtitle "$LABEL_NETWORK_CONFIG" \
               --title "$LABEL_NETWORK_INTERFACE" \
               --menu "\n$LABEL_NETWORK_INTERFACE_CHOICE\n" 14 78 5 \
               "${interface_choice[@]}"  3>&1 1>&2 2>&3)
exitstatus=$?
if [ $exitstatus != 0 ]; then
   return 1
fi
IPV4_ADDRESS="$(ip addr show $INTERFACE | grep "inet " | cut -d " " -f 6 | cut -d "/" -f 1)"
IPV4_ADDRESS_MASK="$(ip addr show $INTERFACE | grep "inet " | cut -d " " -f 6 | cut -d "/" -f 2)"
IPV4_GATEWAY="$(ip route get $IPV4_ADDRESS_TEST_GATEWAY | grep "via" | cut -d " " -f 3)"
IPV6_ADDRESS="$(ip addr show $INTERFACE | grep "inet6 " | grep "global" | cut -d " " -f 6 | cut -d "/" -f 1)"
IPV6_ADDRESS_MASK="$(ip addr show $INTERFACE | grep "inet6 " | grep "global" | cut -d " " -f 6 | cut -d "/" -f 2)"
IPV6_GATEWAY="$(ip -6 route get $IPV6_ADDRESS_TEST_GATEWAY | grep "via" | cut -d " " -f 5)"
