#!/usr/bin/env bash

. lib/include_default

apt update
export DEBIAN_FRONTEND=noninteractive


if [ "$GUACAMOLE_INSTALL_MODE" == "Docker" ]; then
    for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do apt-get remove -y $pkg; done
    apt-get install -y ca-certificates curl
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
fi

apt install -y $GUACAMOLE_DEPENDENCIES

if [ $? != 0 ]; then
    shw_err "apt-get failed to install all required dependencies!"
    exit 1
fi

if [ "$GUACAMOLE_INSTALL_MODE" == "Native" ]; then
    GUACAMOLE_SERVER_FILE="/tmp/guacamole-server.tar.gz"
    GUACAMOLE_CLIENT_FILE="/var/lib/$TOMCAT_VERSION/webapps/guacamole.war"

    if [ ! -f  "$GUACAMOLE_SERVER_FILE" ]; then
        shw_warn " -- Downloading guacamole-server..." 
        wget "$GUACAMOLE_SERVER_URL" -O "$GUACAMOLE_SERVER_FILE"
    fi
    shw_warn " -- Extracting guacamole-server..." 
    tar -xzf "$GUACAMOLE_SERVER_FILE" -C /tmp/
    cd /tmp/guacamole-server-$GUACAMOLE_CURRENT_VERSION/
    shw_warn " -- Autoreconf guacamole-server..." 
    autoreconf -fi
    shw_warn " -- Configure guacamole-server..." 
    ./configure --with-systemd-dir=/etc/systemd/system
    #./configure --with-init-dir=/etc/init.d
    shw_warn " -- Make guacamole-server..." 
    make
    shw_warn " -- Installing guacamole-server..."
    make install

    if [ ! -f  "$GUACAMOLE_CLIENT_FILE" ]; then
        shw_warn " -- Downloading guacamole-client..." 
        wget "$GUACAMOLE_CLIENT_URL" -O "$GUACAMOLE_CLIENT_FILE"
    fi
    ldconfig

    mkdir -v /etc/guacamole
    mkdir -v /etc/guacamole/{lib,extensions}

    echo "[server]" > /etc/guacamole/guacd.conf
    echo "bind_host = 0.0.0.0" >> /etc/guacamole/guacd.conf
    echo "bind_port = 4822" >> /etc/guacamole/guacd.conf

    for auth_extension in $GUACAMOLE_AUTH_SELECTED; do
        if [[ "$auth_extension" == "simple" ]]; then
            echo "<user-mapping><authorize></authorize></user-mapping>" > /etc/guacamole/user-mapping.xml
        else             
            shw_warn "!!! TO-DO wget $auth_extension !!!" # wget "https://apache.org/dyn/closer.lua/guacamole/$GUACAMOLE_CURRENT_VERSION/binary/guacamole-auth-$auth_extension-$GUACAMOLE_CURRENT_VERSION.tar.gz?action=download" -O /tmp/guacamole-auth-$auth_extension-$GUACAMOLE_CURRENT_VERSION.tar.gz
        fi        
    done


    # Configure startup
    systemctl start guacd
    systemctl enable guacd



fi



#wget "$GUACAMOLE_CLIENT_URL" -O /tmp/guacamole-client.tar.gz


