#!/usr/bin/env bash

. lib/include_default

OPT_JOIN_DOMAIN=$(whiptail \
                    --title "$LABEL_ACTIVE_DIRECTORY" \
                    --backtitle "$LABEL_BACKTITLE" \
                    --menu "\n$LABEL_AD_DS_MODE_CHOICE\n\n" 15 78 3 \
                    "NEW" "$LABEL_AD_DS_ADD_NEW_FOREST"   \
                    "JOIN" "$LABEL_AD_DS_JOIN_DOMAIN"  \
                     3>&1 1>&2 2>&3) 

if [[ $OPT_JOIN_DOMAIN == *NEW* ]]; then
    JOIN_DOMAIN="0"
    IP_ADDRESS_PDC_EMULATOR="127.0.0.1"
fi

if [[ $OPT_JOIN_DOMAIN == *JOIN* ]]; then
    JOIN_DOMAIN="1" 
    IP_ADDRESS_PDC_EMULATOR=$(whiptail --backtitle "$LABEL_BACKTITLE" \
                                        --inputbox "\n$LABEL_PDC_EMULATOR_CHOICE\n\n" 13 65 \
                                        $IP_ADDRESS_PDC_EMULATOR \
                                        --title "IP_ADDRESS_PDC_EMULATOR" 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        echo "IP_ADDRESS_PDC_EMULATOR = $IP_ADDRESS_PDC_EMULATOR" 
    else
        exit 0
    fi  
fi
if [[ $OPT_JOIN_DOMAIN == "" ]]; then
    exit 1
fi
