#!/usr/bin/env bash

. lib/include_default


# =================================================================
DNS_BACKEND=$(whiptail \
                    --title "$LABEL_ACTIVE_DIRECTORY" \
                    --backtitle "$LABEL_BACKTITLE" \
                    --menu "\n$LABEL_AD_DS_DNS_BACKEND\n\n"  16 55 3 \
                    "BIND9_DLZ" "Bind DNS"   \
                    "SAMBA_INTERNAL" "Samba Internal DNS"  \
                     3>&1 1>&2 2>&3) 

[ -z "$DNS_BACKEND" ] && exit 1

# =================================================================
DNS_FORWARDER=$(grep "nameserver" /etc/resolv.conf | sed  's/nameserver //g' )
DNS_FORWARDER=$(inputbox "DNS_FORWARDER" \
                         "$LABEL_DNS_FORWARDERS_CHOICE" \
                         "$LABEL_BACKTITLE" 14 55 \
                         "$DNS_FORWARDER" )
[ -z "$DNS_FORWARDER" ] && exit 1
# =================================================================

DNS_REALM=$(cat /etc/resolv.conf | grep "search" | cut -f 2 -d " ")
DNS_REALM=$(inputbox "DNS_REALM" \
                         "$LABEL_DNS_REALM_CHOICE" \
                         "$LABEL_BACKTITLE" 14 55 \
                         "$DNS_REALM" )
[ -z "$DNS_REALM" ] && exit 1

# =================================================================
NETBIOS_NAME=$(echo "${DNS_REALM^^}" | cut -d "." -f 1)
NETBIOS_NAME=$(inputbox "NETBIOS_NAME" \
                "$LABEL_NETBIOS_CHOICE" \
                "$LABEL_BACKTITLE"  13 55 \
                "$NETBIOS_NAME" )

[ -z "$NETBIOS_NAME" ] && exit 1