#!/usr/bin/env bash

. lib/include_default

if [[ "$JOIN_DOMAIN" == "0"  ]]; then
    DOMAIN_LEVEL=$(whiptail --backtitle "$LABEL_ACTIVE_DIRECTORY" --menu "$LABEL_DOMAIN_FUNCTIONAL_LEVEL" 18 78 9 \
            "(default)" "$LABEL_DOMAIN_LEVEL_DEFAULT"  \
            "2012_R2" "Windows Server 2012 R2"   \
            "2012" "Windows Server 2012"   \
            "2008_R2" "Windows Server 2008 R2"   \
            "2008" "Windows Server 2008"   \
            "2003" "Windows Server 2003"   \
            3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        echo "DOMAIN_LEVEL = $DOMAIN_LEVEL" 
    else
        exit 0
    fi
fi